### ISSUE TITLE
Špatné zobrazení obrázku rest api

### ISSUE THREAD

**Issue by Pedro-Martillos** [SamuelFoc/Cerebro-Stream#8]
Když kliknu na Back End -> REST-API - špatně se zobrazí logo (problém dál pokračuje, když klikáš na cokoliv v REST-API), ostatní loga jsou OK.
![problem_rest_api](https://user-images.githubusercontent.com/127335979/223786203-befaff87-da9b-4869-9a5f-5a0bcfad7276.png)

**Comment by SamuelFoc** [comment]
Problém vyriešený, zmenený názov obrázku z RestApiIcon.png => RESAPIIcon.png.
