### ISSUE TITLE
Na profil LinkedIn dole se nedá kliknout

### ISSUE THREAD

**Issue by Pedro-Martillos** [SamuelFoc/Cerebro-Stream#9]
Na profil LinkedIn dole se nedá kliknout, stejně tak u emailu by mohlo být rovnou přesměrování do outlooku

**Comment by Pedro-Martillos** [comment]
A ještě k tomu, když zkopiruju ten odkaz, tak page not found na LinkedInu :worried: :running:

**Comment by SamuelFoc** [comment]
To bude asi tým, že Footer nebol zmenený od Mockupu stránky ;) Problém bude vyriešený do 9.3.2023.

**Comment by SamuelFoc** [comment]
Link na LinkedIn obnovený.
